# Generated by Django 2.2.12 on 2020-05-25 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(max_length=8)),
                ('clocation', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('College', models.CharField(max_length=30)),
                ('course_type', models.CharField(max_length=30)),
                ('passing_year', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('cctc', models.CharField(max_length=30)),
                ('ectc', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('job_category', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
                ('Account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
