# Generated by Django 2.2.12 on 2020-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_description', models.CharField(max_length=30)),
                ('job_location', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('course_type', models.CharField(max_length=30)),
                ('passing_year', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('job_category', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
            ],
        ),
    ]
